version: '3.0'
services:
    database:
        labels:
            - traefik.enable=false
        networks:
            - default

    web:
        labels:
            - traefik.enable=true
            - traefik.http.routers.mederic_project_https.tls=true
            - traefik.http.routers.mederic_project_https.tls.certresolver=letsEncrypt
            - traefik.http.routers.mederic_project_https.rule=Host(`mederic-project.mederic-project.ovh`)
            - traefik.http.routers.mederic_project_https.entryPoints=websecure
            - traefik.http.routers.mederic_project_http.rule=Host(`mederic-project.mederic-project.ovh`)
            - traefik.http.routers.mederic_project_http.entryPoints=web
            - traefik.docker.network=proxy
        depends_on:
            - database
            - smtp
        networks:
            - default
            - proxy

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - database
        environment:
            - PMA_HOST=database
        labels:
            - traefik.enable=true
            - traefik.http.routers.mederic_project_phpmyadmin.rule=Host(`phpmyadmin.mederic-project.mederic-project.ovh`)
            - traefik.http.routers.mederic_project_phpmyadmin.entryPoints=web
            - traefik.docker.network=proxy
        networks:
            - default
            - proxy

    smtp:
        image: djfarrelly/maildev:0.13.4
        restart: always
        labels:
            - traefik.enable=true
            - traefik.http.routers.mederic_project_maildev.rule=Host(`maildev.mederic-project.mederic-project.ovh`)
            - traefik.http.routers.mederic_project_maildev.entryPoints=web
            - traefik.http.services.mederic_project_maildev.loadbalancer.server.port=80
            - traefik.docker.network=proxy
        networks:
            - default
            - proxy

networks:
    proxy:
        external:
            name: proxy
